import { Righteous } from 'next/font/google';
import { Bruno_Ace_SC } from 'next/font/google';
import type { Metadata } from "next";
import "./globals.css";

// Load the font
const righteous = Righteous({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-righteous',
});

const brunoAceSC = Bruno_Ace_SC({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-bruno-ace-sc',
});

export const metadata: Metadata = {
  title: "Portfolio By Yash",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${righteous.variable} ${brunoAceSC.variable}`}>
      <body className="antialiased">
        {children}
      </body>
    </html>
  );
}
